
CREATE TABLE IF NOT EXISTS room_users (
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	room_id UUID REFERENCES rooms(id) ON DELETE CASCADE ON UPDATE CASCADE,
	user_id UUID REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);
